### ISSUE TITLE
System.EntryPointNotFoundException when running /psi example on Windows 7 

### ISSUE THREAD

**Issue by xiangzhi** [microsoft/psi#24]
We got an old machine running 64 bit Windows 7 (updated to most recent patch) and wanted to try out /psi on it. I installed Visual Studio 2019 on it and created a new package according to the first example in the [tutorial](https://microsoft.github.io/psi/tutorials/). The package targets .NET Core 2.1 and is a console application. We added the default code:
```
using Microsoft.Psi;
```
```
static void Main(string[] args)
{
    using (var p = Pipeline.Create())
    {
        var timer = Timers.Timer(p, TimeSpan.FromSeconds(0.1));
        timer.Do(t => Console.WriteLine(t));
        p.Run();
    }
}
```
The package was built successfully but when it start running, it threw an exception:`System.EntryPointNotFoundException: 'Unable to find an entry point named 'GetSystemTimePreciseAsFileTime' in DLL 'kernel32.dll'.'` at the line ` using (var p = Pipeline.Create())`. A quick online search seemed to suggest that it's due to `GetSystemTimePreciseAsFileTime` doesn't exist in Windows 7. Could you validate whether this is true and the only way to solve it is through upgrading it to Window 10?

I also tried changing the platform target to x64 in Build and it still threw the same exception.

 Exception details:
```
System.EntryPointNotFoundException
  HResult=0x80131523
  Message=Unable to find an entry point named 'GetSystemTimePreciseAsFileTime' in DLL 'kernel32.dll'.
  Source=Microsoft.Psi
  StackTrace:
   at Microsoft.Psi.Platform.Windows.HighResolutionTime.GetSystemTimePreciseAsFileTime(Int64& systemTimeAsFileTime)
   at Microsoft.Psi.Platform.Windows.HighResolutionTime.SystemTime()
   at Microsoft.Psi.Clock..ctor(DateTime virtualNow, Single replaySpeedFactor)
   at Microsoft.Psi.Scheduling.Scheduler..ctor(Func`2 errorHandler, Int32 threadCount, Boolean allowSchedulingOnExternalThreads, String name, Clock clock)
   at Microsoft.Psi.Pipeline..ctor(String name, DeliveryPolicy deliveryPolicy, Int32 threadCount, Boolean allowSchedulingOnExternalThreads)
   at Microsoft.Psi.Pipeline.Create(String name, DeliveryPolicy deliveryPolicy, Int32 threadCount, Boolean allowSchedulingOnExternalThreads)
   at PsiExample1.Program.Main(String[] args) in C:\Users\xiangzht\source\repos\PsiExample1\PsiExample1\Program.cs:line 10
```

**Comment by chitsaw** [comment]
Correct. The GetSystemTimePreciseAsFileTime API was introduced in Windows 8. We should document the minimum OS version requirements.
