### ISSUE TITLE
Double Left Click of Psi Studio 3D Visualization Crashes Psi Studio

### ISSUE THREAD

**Issue by xiangzhi** [microsoft/psi#71]
**Steps to Recreate:**
1. Open PsiStudio
2. Load a PsiStore that has a 3D stream (Kinect Bodies, Coordinate System).
3. Visualize the 3D stream.
4. Left click twice on the visualized 3d.
5. PsiStudio will crash.

Here's the print out from the exception
```
System.ArgumentException
  HResult=0x80070057
  Message=Specified Visual is already a child of another Visual or the root of a CompositionTarget.
  Source=PresentationCore
  StackTrace:
   at System.Windows.Media.Media3D.Visual3DCollection.VerifyAPIForAdd(Visual3D value)
   at System.Windows.Media.Media3D.Visual3DCollection.Add(Visual3D value)
   at Microsoft.Psi.Visualization.Views.XYZVisualizationPanelView.AddVisualForVisualizationObject(VisualizationObject visualizationObject) in C:\Users\Zhi\source\repos\CMU-TBD\psi\Sources\Visualization\Microsoft.Psi.Visualization.Common.Windows\Views\XYZVisualizationPanelView.xaml.cs:line 43

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.Psi.Visualization.Views.XYZVisualizationPanelView.AddVisualForVisualizationObject(Microsoft.Psi.Visualization.VisualizationObjects.VisualizationObject) in XYZVisualizationPanelView.xaml.cs
```

It seem to only affect the 3D visualization, as other types of visualization doesn't have this problem. My current work around is to not accidentally double left-click the visualization, but mistake still happens.

**Comment by chitsaw** [comment]
@xiangzhi This should be fixed now, but please reopen this issue if it still occurs. Thanks!
