### ISSUE TITLE
[Bug] Image Resize Operation doesn't work on Images with PixelFormat.Gray_8bpp

### ISSUE THREAD

**Issue by xiangzhi** [microsoft/psi#82]
The following exception is thrown when I try to resize a grayscale image
```
System.Exception
  HResult=0x80131500
  Message=A Graphics object cannot be created from an image that has an indexed pixel format.
  Source=System.Drawing
  StackTrace:
   at System.Drawing.Graphics.FromImage(Image image)
   at Microsoft.Psi.Imaging.Operators.Resize(Image image, Image destImage, Single newWidth, Single newHeight, SamplingMode mode) in C:\Users\Zhi\Source\Repos\CMU-TBD\psi\Sources\Imaging\Microsoft.Psi.Imaging\ImageExtensions.cs:line 352

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.Psi.Imaging.Operators.Resize(Microsoft.Psi.Imaging.Image, Microsoft.Psi.Imaging.Image, float, float, Microsoft.Psi.Imaging.SamplingMode) in ImageExtensions.cs
```
It only happens when I convert it to grayscale than resize. The code works when the operations are done in reverse. 
```
 k4a1.ColorImage.ToGray().Resize(1920, 1080).EncodeJpeg(quality: 80).Write("k4a1", store); // Throw Exceptions
 k4a2.ColorImage.Resize(1920, 1080).ToGray().EncodeJpeg(quality: 80).Write("k4a2", store); // Works
```
I got a workaround but just letting y'all know if it is not an known issue.

**Comment by chitsaw** [comment]
Thanks for reporting this bug. It's been fixed by #87
